"""Default picking rows (Goals sheet). Used by `python -m app.seed_picking`."""

from __future__ import annotations

import uuid

# bucket: etf_reit_fund | value_blue_chips
DEFAULT_PICKING_ROWS: list[dict[str, str]] = [
    {
        "id": str(uuid.uuid5(uuid.NAMESPACE_URL, "picking:voo")),
        "bucket": "etf_reit_fund",
        "name": "Vanguard 500",
        "ticker": "VOO",
        "industry": "ETF",
        "pe": "",
        "eps": "",
        "beta": "",
        "div_yield": "1.28",
        "strong_buy_until": "",
        "may_buy_until": "",
        "buy_right_now": "",
        "price_goal_1y": "",
        "price_goal_5y": "",
        "notes": "",
    },
    {
        "id": str(uuid.uuid5(uuid.NAMESPACE_URL, "picking:schd")),
        "bucket": "etf_reit_fund",
        "name": "Schwab U.S. Dividend",
        "ticker": "SCHD",
        "industry": "ETF",
        "pe": "",
        "eps": "",
        "beta": "",
        "div_yield": "3.33",
        "strong_buy_until": "",
        "may_buy_until": "",
        "buy_right_now": "",
        "price_goal_1y": "",
        "price_goal_5y": "100",
        "notes": "",
    },
    {
        "id": str(uuid.uuid5(uuid.NAMESPACE_URL, "picking:vici")),
        "bucket": "etf_reit_fund",
        "name": "VICI Properties Inc",
        "ticker": "VICI",
        "industry": "REIT",
        "pe": "",
        "eps": "",
        "beta": "",
        "div_yield": "5.34",
        "strong_buy_until": "28",
        "may_buy_until": "30",
        "buy_right_now": "",
        "price_goal_1y": "33",
        "price_goal_5y": "50",
        "notes": "",
    },
    {
        "id": str(uuid.uuid5(uuid.NAMESPACE_URL, "picking:smh")),
        "bucket": "etf_reit_fund",
        "name": "VanEck Semiconductor",
        "ticker": "SMH",
        "industry": "ETF",
        "pe": "",
        "eps": "",
        "beta": "",
        "div_yield": "0.29",
        "strong_buy_until": "",
        "may_buy_until": "",
        "buy_right_now": "",
        "price_goal_1y": "",
        "price_goal_5y": "",
        "notes": "",
    },
    {
        "id": str(uuid.uuid5(uuid.NAMESPACE_URL, "picking:aapl")),
        "bucket": "value_blue_chips",
        "name": "Apple",
        "ticker": "AAPL",
        "industry": "Consumer Electronics",
        "pe": "33.9",
        "eps": "6.27",
        "beta": "1.06",
        "div_yield": "0.44",
        "strong_buy_until": "",
        "may_buy_until": "",
        "buy_right_now": "",
        "price_goal_1y": "200",
        "price_goal_5y": "300",
        "notes": "4, айфон -2%, сервисы в +, падение продаж только в Китае. Цена высокая пока.",
    },
    {
        "id": str(uuid.uuid5(uuid.NAMESPACE_URL, "picking:googl")),
        "bucket": "value_blue_chips",
        "name": "Google",
        "ticker": "GOOGL",
        "industry": "Internet Content & Info",
        "pe": "29.42",
        "eps": "13.11",
        "beta": "1.26",
        "div_yield": "0.48",
        "strong_buy_until": "",
        "may_buy_until": "",
        "buy_right_now": "",
        "price_goal_1y": "300",
        "price_goal_5y": "600",
        "notes": "Реклама, клауд, серч, сервисы - все +2.5%, бит по eps",
    },
    {
        "id": str(uuid.uuid5(uuid.NAMESPACE_URL, "picking:ko")),
        "bucket": "value_blue_chips",
        "name": "Coca Cola",
        "ticker": "KO",
        "industry": "Beverages",
        "pe": "24.74",
        "eps": "3.18",
        "beta": "0.35",
        "div_yield": "2.75",
        "strong_buy_until": "61.2",
        "may_buy_until": "64.8",
        "buy_right_now": "",
        "price_goal_1y": "72",
        "price_goal_5y": "",
        "notes": "5, все растет, 4-7% - ревенью, маржа +0.1%. Есть одно но, больше денег из-за повышения цены, а не кол-ва продаж.",
    },
    {
        "id": str(uuid.uuid5(uuid.NAMESPACE_URL, "picking:msft")),
        "bucket": "value_blue_chips",
        "name": "Microsoft",
        "ticker": "MSFT",
        "industry": "Software",
        "pe": "24.68",
        "eps": "16.79",
        "beta": "1.1",
        "div_yield": "0.6",
        "strong_buy_until": "343",
        "may_buy_until": "403",
        "buy_right_now": "",
        "price_goal_1y": "475",
        "price_goal_5y": "900",
        "notes": "Ревенью +18%, клауды +20%, бит по eps",
    },
    {
        "id": str(uuid.uuid5(uuid.NAMESPACE_URL, "picking:bac")),
        "bucket": "value_blue_chips",
        "name": "Bank of America",
        "ticker": "BAC",
        "industry": "Banks",
        "pe": "13.31",
        "eps": "4",
        "beta": "1.21",
        "div_yield": "2.65",
        "strong_buy_until": "",
        "may_buy_until": "",
        "buy_right_now": "",
        "price_goal_1y": "45",
        "price_goal_5y": "58",
        "notes": "5+, рост всех категорий, rev - 6%, oct 10-12%",
    },
    {
        "id": str(uuid.uuid5(uuid.NAMESPACE_URL, "picking:amzn")),
        "bucket": "value_blue_chips",
        "name": "Amazon",
        "ticker": "AMZN",
        "industry": "Internet Retail",
        "pe": "32.08",
        "eps": "8.37",
        "beta": "1.47",
        "div_yield": "0",
        "strong_buy_until": "225",
        "may_buy_until": "230",
        "buy_right_now": "",
        "price_goal_1y": "260",
        "price_goal_5y": "530",
        "notes": "Stores +6-9%, ADV +22%, Subscriptions +12%, AWS +20%. Gross Profit +16%, Net +31%, Operating costs +15%, 200bln on CAPEX (AI)",
    },
    {
        "id": str(uuid.uuid5(uuid.NAMESPACE_URL, "picking:ma")),
        "bucket": "value_blue_chips",
        "name": "Mastercard",
        "ticker": "MA",
        "industry": "Finance Services",
        "pe": "29.99",
        "eps": "16.52",
        "beta": "0.76",
        "div_yield": "0.77",
        "strong_buy_until": "410",
        "may_buy_until": "520",
        "buy_right_now": "",
        "price_goal_1y": "611",
        "price_goal_5y": "1150",
        "notes": "",
    },
    {
        "id": str(uuid.uuid5(uuid.NAMESPACE_URL, "picking:hood")),
        "bucket": "value_blue_chips",
        "name": "Robinhood Markets Inc",
        "ticker": "HOOD",
        "industry": "Finance Services",
        "pe": "35.57",
        "eps": "2.07",
        "beta": "2.29",
        "div_yield": "0",
        "strong_buy_until": "",
        "may_buy_until": "",
        "buy_right_now": "",
        "price_goal_1y": "75",
        "price_goal_5y": "150",
        "notes": "5, Revenue +77%, net - 50%, eps +100%. Но еще не так, как в 2024 март, битты, но не большие.",
    },
    {
        "id": str(uuid.uuid5(uuid.NAMESPACE_URL, "picking:tsla")),
        "bucket": "value_blue_chips",
        "name": "Tesla",
        "ticker": "TSLA",
        "industry": "Auto Manufacturers",
        "pe": "357.13",
        "eps": "1.09",
        "beta": "1.79",
        "div_yield": "0",
        "strong_buy_until": "",
        "may_buy_until": "",
        "buy_right_now": "",
        "price_goal_1y": "300",
        "price_goal_5y": "",
        "notes": "-20% revenue, -71% net income, -13% отпр. машин",
    },
]
